apiVersion: v1
kind: Secret
metadata:
 name: docker-registry-secret
data:
 .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImJYVnliMlJpWlhrNmVuWmxjakl3TVRJPSIKCQl9Cgl9LAoJIkh0dHBIZWFkZXJzIjogewoJCSJVc2VyLUFnZW50IjogIkRvY2tlci1DbGllbnQvMTguMDMuMS1jZSAobGludXgpIgoJfSwKCSJjcmVkSGVscGVycyI6IHsKCQkiYXNpYS5nY3IuaW8iOiAiZ2NyIiwKCQkiZXUuZ2NyLmlvIjogImdjciIsCgkJImdjci5pbyI6ICJnY3IiLAoJCSJzdGFnaW5nLWs4cy5nY3IuaW8iOiAiZ2NyIiwKCQkidXMuZ2NyLmlvIjogImdjciIKCX0KfQ==
type: kubernetes.io/dockerconfigjson
